name: Deploy to dev
on:
  push:
    branches:
     - dev

jobs:
  ftp-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: FTP Upload
        uses: wbeuil/ftp-deploy-action@v3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          remote-dir: /public_html/dummy_project/dev