name: Reset Branches on New Tag

on:
  push:
    tags:
      - '*'

jobs:
  reset-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Debug Branches
        run: |
          git branch --list
          git remote show origin

      - name: Reset dev Branch to main
        run: |
          git checkout dev
          git reset --hard origin/main
          git push --force origin dev

      - name: Reset stage Branch to main
        run: |
          git checkout stage
          git reset --hard origin/main
          git push --force origin stage
